-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-10 18:11:41 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
--  student name:    Shenyi Zhang
--  student id:     30359953

set echo on
spool mau_schema_output.txt

DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE artwork CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE exhibition CASCADE CONSTRAINTS;

DROP TABLE gallery CASCADE CONSTRAINTS;

DROP TABLE mediades CASCADE CONSTRAINTS;

DROP TABLE status CASCADE CONSTRAINTS;

DROP TABLE style CASCADE CONSTRAINTS;

DROP TABLE transaction CASCADE CONSTRAINTS;

CREATE TABLE artist (
    artist_code            NUMBER(7) NOT NULL,
    artist_fname           VARCHAR2(20) NOT NULL,
    artist_lname           VARCHAR2(20) NOT NULL,
    artist_phone           CHAR(9),
    artist_current_stock   NUMBER(5) NOT NULL,
    artist_str             VARCHAR2(20) NOT NULL,
    artist_town            VARCHAR2(20) NOT NULL,
    artist_state           VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN artist.artist_code IS
    'artist code';

COMMENT ON COLUMN artist.artist_fname IS
    'artist first name';

COMMENT ON COLUMN artist.artist_lname IS
    'artist last  name';

COMMENT ON COLUMN artist.artist_phone IS
    'artist phone number';

COMMENT ON COLUMN artist.artist_current_stock IS
    'amount of artwork of one artist';

COMMENT ON COLUMN artist.artist_str IS
    'artist street';

COMMENT ON COLUMN artist.artist_town IS
    'artist town';

COMMENT ON COLUMN artist.artist_state IS
    'artist state';

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_code );

CREATE TABLE artwork (
    art_no          NUMBER(4) NOT NULL,
    artist_code     NUMBER(7) NOT NULL,
    art_add_date    DATE NOT NULL,
    art_title       VARCHAR2(50) NOT NULL,
    art_min_price   VARCHAR2(20) NOT NULL,
    style_name      VARCHAR2(20) NOT NULL,
    mediades_name   VARCHAR2(20) NOT NULL
);

ALTER TABLE artwork ADD CONSTRAINT chk_art_min_price CHECK ( art_min_price > 0 )
;

COMMENT ON COLUMN artwork.art_no IS
    'artword number';

COMMENT ON COLUMN artwork.artist_code IS
    'artist code';

COMMENT ON COLUMN artwork.art_add_date IS
    'artwork first time added date';

COMMENT ON COLUMN artwork.art_title IS
    'artwork title';

COMMENT ON COLUMN artwork.art_min_price IS
    'artwork minmum sale price';

COMMENT ON COLUMN artwork.style_name IS
    'style name';

COMMENT ON COLUMN artwork.mediades_name IS
    'media description';

ALTER TABLE artwork ADD CONSTRAINT artwork_pk PRIMARY KEY ( art_no,
                                                            artist_code );

CREATE TABLE customer (
    cus_id               NUMBER NOT NULL,
    cus_fname            VARCHAR2(20) NOT NULL,
    cus_lname            VARCHAR2(20) NOT NULL,
    cus_str              VARCHAR2(20) NOT NULL,
    cus_town             VARCHAR2(20) NOT NULL,
    cus_state            VARCHAR2(20) NOT NULL,
    cus_phone            CHAR(9) NOT NULL,
    cus_bussiness_name   VARCHAR2(20)
);

COMMENT ON COLUMN customer.cus_id IS
    'customer id';

COMMENT ON COLUMN customer.cus_fname IS
    'customer first name';

COMMENT ON COLUMN customer.cus_lname IS
    'customer family name';

COMMENT ON COLUMN customer.cus_str IS
    'customer street address';

COMMENT ON COLUMN customer.cus_town IS
    'customer town';

COMMENT ON COLUMN customer.cus_state IS
    'customer state';

COMMENT ON COLUMN customer.cus_phone IS
    'customer phone';

COMMENT ON COLUMN customer.cus_bussiness_name IS
    'customer bussiness name';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( cus_id );

CREATE TABLE exhibition (
    exh_id        NUMBER(7) NOT NULL,
    exh_start     DATE NOT NULL,
    exh_end       DATE,
    exh_fea       VARCHAR2(3) NOT NULL,
    art_no        NUMBER(4) NOT NULL,
    gal_id        NUMBER(7) NOT NULL,
    artist_code   NUMBER(7) NOT NULL
);

ALTER TABLE exhibition
    ADD CONSTRAINT chk_exh_fea CHECK ( exh_fea IN (
        'NO',
        'YES'
    ) );

COMMENT ON COLUMN exhibition.exh_id IS
    'exhibition id';

COMMENT ON COLUMN exhibition.exh_start IS
    'exhibition start date';

COMMENT ON COLUMN exhibition.exh_end IS
    'exhibition end date';

COMMENT ON COLUMN exhibition.exh_fea IS
    'whether exhibition is recorded in catlog. can only be YES/NO';

COMMENT ON COLUMN exhibition.art_no IS
    'artword number';

COMMENT ON COLUMN exhibition.gal_id IS
    'gallery id';

COMMENT ON COLUMN exhibition.artist_code IS
    'artist code';

ALTER TABLE exhibition ADD CONSTRAINT exhibition_pk PRIMARY KEY ( exh_id );

ALTER TABLE exhibition
    ADD CONSTRAINT nk_exh UNIQUE ( art_no,
                                   artist_code,
                                   exh_start );

CREATE TABLE gallery (
    gal_id              NUMBER(7) NOT NULL,
    gal_name            VARCHAR2(20) NOT NULL,
    gal_str             VARCHAR2(20) NOT NULL,
    gal_town            VARCHAR2(20) NOT NULL,
    gal_state           VARCHAR2(20) NOT NULL,
    gal_open            DATE NOT NULL,
    gal_close           DATE NOT NULL,
    gal_manager_fname   VARCHAR2(20) NOT NULL,
    gal_manager_lname   VARCHAR2(20) NOT NULL,
    gal_phone           CHAR(9) NOT NULL,
    gal_paid_per        NUMBER(3, 3) NOT NULL
);

ALTER TABLE gallery ADD CONSTRAINT chk_gal_paid_per CHECK ( gal_paid_per > 0 );

COMMENT ON COLUMN gallery.gal_id IS
    'gallery id';

COMMENT ON COLUMN gallery.gal_name IS
    'gallery name';

COMMENT ON COLUMN gallery.gal_str IS
    'gallery stress address';

COMMENT ON COLUMN gallery.gal_town IS
    'gallary town address';

COMMENT ON COLUMN gallery.gal_state IS
    'gallery state';

COMMENT ON COLUMN gallery.gal_open IS
    'gallery open tiem';

COMMENT ON COLUMN gallery.gal_close IS
    'gallery close time';

COMMENT ON COLUMN gallery.gal_manager_fname IS
    'gallery manager first name';

COMMENT ON COLUMN gallery.gal_manager_lname IS
    'gallery manager last name';

COMMENT ON COLUMN gallery.gal_phone IS
    'gallery phone number';

COMMENT ON COLUMN gallery.gal_paid_per IS
    'gallery paid percentage';

ALTER TABLE gallery ADD CONSTRAINT gallery_pk PRIMARY KEY ( gal_id );

CREATE TABLE mediades (
    mediades_name VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN mediades.mediades_name IS
    'media description';

ALTER TABLE mediades ADD CONSTRAINT mediades_pk PRIMARY KEY ( mediades_name );

CREATE TABLE status (
    status_date   DATE NOT NULL,
    art_no        NUMBER(4) NOT NULL,
    status        VARCHAR2(20) NOT NULL,
    gal_id        NUMBER(7),
    artist_code   NUMBER(7) NOT NULL
);

ALTER TABLE status
    ADD CONSTRAINT chk_status CHECK ( status IN (
        'in storage',
        'in transit',
        'on display',
        'returned',
        'sold'
    ) );

COMMENT ON COLUMN status.status_date IS
    'the date of the time  the status record for';

COMMENT ON COLUMN status.art_no IS
    'artword number';

COMMENT ON COLUMN status.status IS
    'status';

COMMENT ON COLUMN status.gal_id IS
    'gallery id';

COMMENT ON COLUMN status.artist_code IS
    'artist code';

ALTER TABLE status
    ADD CONSTRAINT status_pk PRIMARY KEY ( status_date,
                                           art_no,
                                           artist_code );

CREATE TABLE style (
    style_name    VARCHAR2(20) NOT NULL,
    style_name1   VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN style.style_name IS
    'style name';

COMMENT ON COLUMN style.style_name1 IS
    'style name';

ALTER TABLE style ADD CONSTRAINT style_pk PRIMARY KEY ( style_name );

CREATE TABLE transaction (
    trans_id      NUMBER(7) NOT NULL,
    trans_date    DATE NOT NULL,
    exh_id        NUMBER(7) NOT NULL,
    cus_id        NUMBER NOT NULL,
    trans_price   VARCHAR2(20)
);

COMMENT ON COLUMN transaction.trans_id IS
    'transaction id';

COMMENT ON COLUMN transaction.trans_date IS
    'transaction date';

COMMENT ON COLUMN transaction.exh_id IS
    'exhibition id';

COMMENT ON COLUMN transaction.cus_id IS
    'customer id';

COMMENT ON COLUMN transaction.trans_price IS
    'transaction price';

CREATE UNIQUE INDEX transaction__idx ON
    transaction (
        exh_id
    ASC );

ALTER TABLE transaction ADD CONSTRAINT transaction_pk PRIMARY KEY ( trans_id );

ALTER TABLE artwork
    ADD CONSTRAINT art_artist FOREIGN KEY ( artist_code )
        REFERENCES artist ( artist_code );

ALTER TABLE exhibition
    ADD CONSTRAINT art_exh FOREIGN KEY ( art_no,
                                         artist_code )
        REFERENCES artwork ( art_no,
                             artist_code );

ALTER TABLE status
    ADD CONSTRAINT art_stat FOREIGN KEY ( art_no,
                                          artist_code )
        REFERENCES artwork ( art_no,
                             artist_code );

ALTER TABLE transaction
    ADD CONSTRAINT "CUS-TRANS" FOREIGN KEY ( cus_id )
        REFERENCES customer ( cus_id );

ALTER TABLE exhibition
    ADD CONSTRAINT gal_exh FOREIGN KEY ( gal_id )
        REFERENCES gallery ( gal_id );

ALTER TABLE artwork
    ADD CONSTRAINT media_artwork FOREIGN KEY ( mediades_name )
        REFERENCES mediades ( mediades_name );

ALTER TABLE style
    ADD CONSTRAINT relation_11 FOREIGN KEY ( style_name1 )
        REFERENCES style ( style_name );

ALTER TABLE status
    ADD CONSTRAINT stat_gal FOREIGN KEY ( gal_id )
        REFERENCES gallery ( gal_id );

ALTER TABLE artwork
    ADD CONSTRAINT style_artwork FOREIGN KEY ( style_name )
        REFERENCES style ( style_name );

ALTER TABLE transaction
    ADD CONSTRAINT trans_exh FOREIGN KEY ( exh_id )
        REFERENCES exhibition ( exh_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             1
-- ALTER TABLE                             24
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
spool off
set echo off